routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
	$menus = \App\Menu::all();
    return view('welcome', compact('menus'));
})->name('homepage');


Route::resource("/menu", "MenuController");
Route::resource("/dishes", "DishController");


Route::get('/contacts', function() {
  $contacts = \App\Contacts::first();

  return view('contacts.index', compact('contacts'));
})->name('contacts');


Auth::routes();

Route::get('/home', 'HomeController@index');

Route::post('/cart', 'CartController@store')->name('cart.store');

Route::post('/cartDestroyAll', 'CartController@destroyAll')->name('cart.destroyAll');

Route::post('/cartDestroy', 'CartController@destroy')->name('cart.destroy');

Route::get('checkout', function () {
	return view('checkout'); 
})->name('checkout');

Route::post('/cartUpdate', 'CartController@update')->name('cart.update');

Route::resource('/order', 'OrderController');

app/Menu.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{

	protected $fillable = [
		'title',
		'description',
		'image'
	];

    public function dishes(){
    	return $this->hasMany('App\Dish'); 
    }
}

app/Http/Controllers/MenuController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class MenuController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // return view('menu.index');

        $menu = \App\Menu::all();

        return view('menu.index', compact('menu'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('menu.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $new_menu = \App\Menu::create($request->all());

        return redirect()->route('menu.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $menu = \App\Menu::find($id);

        //gauti patiekalus pagal kategorijas
        $dishes = \App\Dish::where('menu_id', $id)->get();

        return view('menu.show', compact('menu', 'dishes'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $menu = \App\Menu::find($id);
        return view('menu.create', compact('menu'));;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $menu = \App\Menu::find($id)->update($request->all());

        return redirect()->route('menu.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $menu = \App\Menu::find($id)->delete();
        return redirect()->route('menu.index');
    }
}

resources/views/menu/create.blade.php
@extends("layouts.app")
@section("content")
<h3>{{ isset($menu) ? 'Edit meniu' : 'Add meniu' }}</h3>
@if(isset($menu))
    {{ Form::open(['route' => ['menu.update', $menu->id], 'method' => "POST"]) }}
    {{ Form::hidden('_method', 'PUT') }}
@else
    {{ Form::open(['route' => 'menu.store', 'method' => "POST"]) }}
@endif
{{ csrf_field() }}
    {{ Form::label('title', 'Title') }}
    @if(isset($menu))
        {{ Form::text('title', ($menu['title']), ['class' => 'form-control']) }}
    @else
        {{ Form::text('title', '', ['class' => 'form-control']) }}
    @endif

    {{ Form::label('description', 'Description') }}
    @if(isset($menu))
        {{ Form::text('description', ($menu['description']), ['class' => 'form-control']) }}
    @else
        {{ Form::text('description', '', ['class' => 'form-control']) }}
    @endif

    {{ Form::label('image', 'Image') }}
    @if(isset($menu))
        {{ Form::text('image', ($menu['image']), ['class' => 'form-control']) }}
    @else
        {{ Form::text('image', '', ['class' => 'form-control']) }}
    @endif
<br>
@if(isset($menu))
    {{ Form::submit('Edit menu', ['class' => 'btn btn-primary']) }}
@else
    {{ Form::submit('Add menu', ['class' => 'btn btn-primary']) }}
@endif
{{ Form::close() }}
@if(isset($menu))
    {{ Form::open(['route' => ['menu.destroy', $menu->id], 'method' => "POST"]) }}
    {{ Form::hidden('_method', 'DELETE') }}
            {{ csrf_field() }}
        {{ Form::submit('Delete', ['class' => 'btn btn-danger']) }}
    
@endif
{{ Form::close() }}
@endsection

resources/views/menu/index.blade.php
@extends('layouts.app')

@section('content')

<a href="{{ route('menu.create') }}">Create meniu</a>

<ul>
  @foreach($menu as $menu)
  <li>
    <h3>{{ $menu->title }}</h3>
    
    <a href="{{ route('menu.edit', $menu->id) }}">Edit meniu</a>
    <br>

    <a href="{{ route('menu.show', $menu->id) }}">READ MORE</a>
  </li>
  @endforeach

</ul>

@endsection

resources/views/menu/show.blade.php
@extends ('layouts.app')
@section ('content')

<div class="container">
    <div class="well well-sm">
        <strong>Category Title</strong>
        <div class="btn-group">
            <a href="#" id="list" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-th-list">
            </span>List</a> <a href="#" id="grid" class="btn btn-default btn-sm"><span
                class="glyphicon glyphicon-th"></span>Grid</a>
        </div>
    </div>
    <div id="products" class="row list-group">
        @foreach ($dishes as $index => $dish)
            <div class="item  col-xs-4 col-md-4">
                <div class="thumbnail">
                    <div class="imgClass">
                        <img class="group list-group-image img-responsive" src="{{ $dish->photo }}" alt="" />
                    </div>
                    <div class="caption">
                        <h4 class="group inner list-group-item-heading">
                            {{ $dish->title }}</h4>
                        <p class="group inner list-group-item-text">
                            {{ $dish->description }}</p>
                        <div class="row">
                            <div class="col-xs-12 col-md-4">
                                <p class="lead">
                                    {{ $dish->price }} Euro</p>
                            </div>
                            <div class="col-xs-12 col-md-6">
                                <a data-dish-id="{{ $dish->id }}" class="btn btn-success add-to-cart" href="#">Add to cart</a>                            </div>
                        </div>
                    </div>
                </div>
            </div>

            @if(++$index % 3 == 0)
                </div><div class="row">
            @endif
        @endforeach
    </div>
</div>


@endsection