routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
	$menus = \App\Menu::all();
    return view('welcome', compact('menus'));
})->name('homepage');


Route::resource("/menu", "MenuController");
Route::resource("/dishes", "DishController");


Route::get('/contacts', function() {
  $contacts = \App\Contacts::first();

  return view('contacts.index', compact('contacts'));
})->name('contacts');


Auth::routes();

Route::get('/home', 'HomeController@index');

Route::post('/cart', 'CartController@store')->name('cart.store');

Route::post('/cartDestroyAll', 'CartController@destroyAll')->name('cart.destroyAll');

Route::post('/cartDestroy', 'CartController@destroy')->name('cart.destroy');

Route::get('checkout', function () {
	return view('checkout'); 
})->name('checkout');

Route::post('/cartUpdate', 'CartController@update')->name('cart.update');

Route::resource('/order', 'OrderController');

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
	protected $fillable = [
		'name',
        'table_id',
        'contact_phone',
        'reserved_at',
        'number_of_persons'
        

    ];

    public function user(){
    	return $this->belongsTo('App\User');
    }



      public function orderItems(){
    	return $this->hasMany('App\OrderItem');
    }

    public function table(){
    	return $this->belongsTo('App\Table');
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;
use \App\Order;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $user = Auth::user();

        // ar prisijunges ar ne

        // jei neprisijunges
        if (Auth::guest()) {
        return redirect()->route('register');
        }
        //jeigu prisijunges 

        return view('order.create', compact('user'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validacija
        $this->validate($request, [
        'name' => 'required',
        'table_id' => 'required',
        'contact_phone' => 'required',
        'reserved_at' => 'required|date_format:Y-m-d H:i',
        'number_of_persons' => 'required'
        ]);

        //surinkt duomenis is formos
        $data = $request->all();
        //issaugoti orderi duomenu bazeje
        $user = Auth::user();
        $order = $user->orders()->create($data);

        $cartItems = session()->get('cart.items');

        foreach ($cartItems as $item) {
            $item['dish_id'] = $item['id'];
            $order->orderItems()->create($item);
        }

        $request->session()->forget('cart.items');
        $request->session()->put('cart.total_amount', 0);
        $request->session()->put('cart.total_items', 0);
        //peradresuoja vartotoja i uzsakymo psl
        return redirect()->route('order.show', $order->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $order = Order::find($id);
        

        return view('order.show', compact('order'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/order/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Order data</div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="{{ route('order.store') }}">
                        {{ csrf_field() }}

                        @foreach ($errors->all() as $error)
                            <li>
                                <strong>{{ $error }}</strong>
                            </li>
                        @endforeach

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('table_id') ? ' has-error' : '' }}">
                            <label for="table_id" class="col-md-4 control-label">Table Nr.</label>

                            <div class="col-md-6">

                                {{ Form::select('table_id', ['1' => 'Table 1', 2 => 'Table 2']) }} 

                                @if ($errors->has('table_id'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('table_id') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('contact_phone') ? ' has-error' : '' }}">
                            <label for="contact_phone" class="col-md-4 control-label">Phone number</label>

                            <div class="col-md-6">
                                <input id="contact_phone" type="text" class="form-control" name="contact_phone" value="{{ old('contact_phone','+370') }}" required autofocus>

                                @if ($errors->has('contact_phone'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('contact_phone') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('reserved_at') ? ' has-error' : '' }}">
                            <label for="reserved_at" class="col-md-4 control-label">Reservation: date&time</label>

                            <div class="col-md-6">
                                <input id="reserved_at" type="text" class="form-control" name="reserved_at" required value="{{ old('reserved_at') }}">
                                <p class="help-block">pvz.: 2016-05-22 20:00</p>

                                @if ($errors->has('reserved_at'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('reserved_at') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('number_of_persons') ? ' has-error' : '' }}">
                            <label for="number_of_persons" class="col-md-4 control-label">Number of persons</label>

                            <div class="col-md-6">

                                
                                {{ Form::number('number_of_persons', 2, ['min' => 1]) }}

                                @if ($errors->has('number_of_persons'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('number_of_persons') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                            

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Order
                                </button>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <a href="{{ URL::route('checkout') }}" class="btn btn-default">
                                    Back
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/order/show.blade.php
@extends ('layouts.app')

@section ('content')

	<h3>Kita karta pirk daugiau</h3>

@endsection